--DELETE
/*

DELETE FROM JAVA_CATEGORIA;
DELETE FROM JAVA_PEDIDO;
DELETE FROM JAVA_PRODUTO;
DELETE FROM JAVA_PEDIDODETALHE;

*/

-- CATEGORIAS

INSERT INTO JAVA_CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL, 'PERIFERICOS'); 
INSERT INTO JAVA_CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL, 'HARDWARE');
INSERT INTO JAVA_CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL, 'ACESSORIOS');
INSERT INTO JAVA_CATEGORIA VALUES (CATEGORIA_SEQUENCE.NEXTVAL, 'MONITORES');

-- PRODUTOS

INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 1, 'MOUSE', 'MOUSE PARA COMPUTADOR', 79.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 1, 'TECLADO', 'TECLADO PARA COMPUTADOR', 99.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 1, 'HEADSET', 'HEADSET USB', 49.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 1, 'MICROFONE', 'MICROFONE PARA COMPUTADOR', 399.99);

INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 2, 'PLACA DE VIDEO', 'RTX 3060', 5999.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 2, 'PLACA MAE', 'B-450M GAMING BR', 699.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 2, 'PROCESSADOR', 'RYZEN 5 2600', 849.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 2, 'FONTE', 'TX 750M', 599.99);

INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 3, 'MOUSE PAD', 'MOUSE PAD PEQUENO', 39.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 3, 'MOUSE PAD', 'MOUSE PAD GRANDE', 119.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 3, 'SUPORTE P/ HEADSET', 'SUPORTE PARA HEADSET', 89.99);
INSERT INTO JAVA_PRODUTO VALUES (PRODUTO_SEQUENCE.NEXTVAL, 3, 'HUB', 'USB HUB', 29.99);

-- PEDIDO

INSERT INTO JAVA_PEDIDO VALUES (PEDIDO_SEQUENCE.NEXTVAL, 'HYAN', 'MAUA', '30/10/2022');
INSERT INTO JAVA_PEDIDO VALUES (PEDIDO_SEQUENCE.NEXTVAL, 'CRISTINA', 'MAUA', '25/10/2022');
INSERT INTO JAVA_PEDIDO VALUES (PEDIDO_SEQUENCE.NEXTVAL, 'DUDA', 'SAO BERNARDO', '05/11/2022');
INSERT INTO JAVA_PEDIDO VALUES (PEDIDO_SEQUENCE.NEXTVAL, 'AMANDA', 'SAO BERNARDO', '15/11/2022');
INSERT INTO JAVA_PEDIDO VALUES (PEDIDO_SEQUENCE.NEXTVAL, 'LUCAS', 'SAO PAULO', '26/09/2022');

-- DETALHE

INSERT INTO JAVA_PEDIDODETALHE (ID, PEDIDO_ID, PRODUTO_ID, QUANTIDADE, TOTAL) VALUES (DETALHE_SEQUENCE.NEXTVAL, 1000, 1003, 1, 399.99);
INSERT INTO JAVA_PEDIDODETALHE VALUES (DETALHE_SEQUENCE.NEXTVAL, 1001, 1001, 1, 99.99);
INSERT INTO JAVA_PEDIDODETALHE VALUES (DETALHE_SEQUENCE.NEXTVAL, 1002, 1005, 1, 699.99);
INSERT INTO JAVA_PEDIDODETALHE VALUES (DETALHE_SEQUENCE.NEXTVAL, 1003, 1010, 1, 89.99);
INSERT INTO JAVA_PEDIDODETALHE VALUES (DETALHE_SEQUENCE.NEXTVAL, 1004, 1007, 1, 599.99);

