/*
DROP SEQUENCE CATEGORIA_SEQUENCE;
DROP SEQUENCE PRODUTO_SEQUENCE;
DROP SEQUENCE PEDIDO_SEQUENCE;
DROP SEQUENCE DETALHE_SEQUENCE;
----------------------------------
DROP TABLE JAVA_CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE JAVA_PRODUTO CASCADE CONSTRAINTS;
DROP TABLE JAVA_PEDIDO CASCADE CONSTRAINTS;
DROP TABLE JAVA_PEDIDODETALHE CASCADE CONSTRAINTS;
---------------------------------

*/

--------------SEQUENCES-------------
CREATE SEQUENCE CATEGORIA_SEQUENCE
    MINVALUE 1
    MAXVALUE 999999
    START WITH 1
    CACHE 20;

CREATE SEQUENCE PRODUTO_SEQUENCE
    MINVALUE 1
    MAXVALUE 999999
    START WITH 1000
    CACHE 20;

CREATE SEQUENCE PEDIDO_SEQUENCE
    MINVALUE 1
    MAXVALUE 999999
    START WITH 1000
    CACHE 20;

CREATE SEQUENCE DETALHE_SEQUENCE
    MINVALUE 1
    MAXVALUE 999999
    START WITH 10
    CACHE 20;

--------------- TABLES ------------------------

CREATE TABLE JAVA_CATEGORIA (
    CATEGORIA_ID        NUMBER,
    CATEGORIA           VARCHAR2(50)
);

CREATE TABLE JAVA_PRODUTO (
    PRODUTO_ID          NUMBER,
    CATEGORIA_ID        NUMBER,
    NOME                VARCHAR2(50),
    DESCRICAO           VARCHAR2(50),
    PRECO               NUMBER(10,2)
);

CREATE TABLE JAVA_PEDIDO (
    PEDIDO_ID           NUMBER,
    NOME_CONTATO        VARCHAR2(50),
    ENDERECO_CONTATO    VARCHAR(50),
    DATA                DATE
);

CREATE TABLE JAVA_PEDIDODETALHE(
    ID                  NUMBER,
    PEDIDO_ID           NUMBER,
    PRODUTO_ID          NUMBER,
    QUANTIDADE          NUMBER,
    TOTAL               NUMBER(10,2)
);
    
----------------ALTER TABLE---------------

-- CATEGORIA

ALTER TABLE JAVA_CATEGORIA
    ADD CONSTRAINT FK_CATEGORIA PRIMARY KEY (CATEGORIA_ID);

-- PRODUTO

ALTER TABLE JAVA_PRODUTO
    ADD CONSTRAINT FK_PRODUTO PRIMARY KEY (PRODUTO_ID);
    
ALTER TABLE JAVA_PRODUTO
    ADD CONSTRAINT FK_CATEGORIA_PRODUTO FOREIGN KEY (CATEGORIA_ID)
    REFERENCES JAVA_CATEGORIA (CATEGORIA_ID);
    
-- PEDIDO

ALTER TABLE JAVA_PEDIDO
    ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (PEDIDO_ID);
    
-- DETALHE

ALTER TABLE JAVA_PEDIDODETALHE
    ADD CONSTRAINT PK_DETALHE PRIMARY KEY (ID);
    
ALTER TABLE JAVA_PEDIDODETALHE
    ADD CONSTRAINT FK_PEDIDO_DETALHE FOREIGN KEY (PEDIDO_ID)
    REFERENCES JAVA_PEDIDO(PEDIDO_ID);
    
ALTER TABLE JAVA_PEDIDODETALHE
    ADD CONSTRAINT FK_PRODUTO_DETALHE FOREIGN KEY (PRODUTO_ID)
    REFERENCES JAVA_PRODUTO (PRODUTO_ID);